name: Build and Test Chatbot

on: [push, pull_request]  

jobs:
  build:
    runs-on: windows-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.102'  

      - name: Restore dependencies
        run: dotnet restore  

      - name: Build project
        run: dotnet build C:\Users\adivh\source\repos\ProgPart1\ProgPart1\ --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal    